version: '3.8'

services:
  # 1. MySQL: 存储用户、帖子、关注关系等持久化数据
  mysql:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/mysql:8.0
    container_name: feed-mysql
    restart: always
    ports:
      - "13306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: feed_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - feed-mysql-data:/var/lib/mysql

  # 2. Redis: Feed 流时间线缓存 + API 限流
  redis:
    image: redis:latest
    pull_policy: if_not_present
    container_name: feed-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - feed-redis-data:/data

  # 3. Kafka: 异步解耦发帖 → 写粉丝时间线
  kafka:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/bitnami/kafka:latest
    container_name: feed-kafka
    pull_policy: if_not_present
    restart: always
    ports:
      - "9092:9092"
    environment:
      TZ: Asia/Shanghai
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@feed-kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.100.128:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - feed-kafka-data:/bitnami/kafka

# 声明命名卷
volumes:
  feed-mysql-data:
  feed-redis-data:
  feed-kafka-data: